In [26]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv('customer.csv')

In [28]:
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [29]:
df=df.iloc[:,2:]

In [42]:
df.head(37)

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No
5,Average,School,Yes
6,Good,School,No
7,Poor,School,Yes
8,Average,UG,No
9,Good,UG,Yes


In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_teat=train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [32]:
X_train

,review,education
36,Good,UG
27,Poor,PG
31,Poor,School
14,Poor,PG
19,Poor,PG
32,Average,UG
46,Poor,PG
30,Average,UG
11,Good,UG
0,Average,School


In [33]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School','UG','PG']])

oe.fit(X_train)

X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [34]:
X_train

array([[2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [2., 0.]])

In [35]:
X_test

array([[0., 2.],
       [0., 2.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.]])

In [39]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

le.fit(y_train)

y_train=le.transform(y_train)

In [40]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0])