In [1]:
import numpy as np

In [3]:
# 0D Tensor/Scalar
a = np.array(5)
a

array(5)

In [4]:
# 1D Tensor/Vector
b = np.array([1, 2, 3])
b

array([1, 2, 3])

In [5]:
# 2D Tensor/Matrix
c = np.array([[1, 2],
              [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [6]:
# 3D Tensor
d = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
d.shape

(2, 2, 2)

In [8]:
#4d tensor
tensor_4d = np.zeros((2, 3, 4, 5))

print(tensor_4d)
print(tensor_4d.ndim)
print(tensor_4d.shape)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
4
(2, 3, 4, 5)
